# This is a basic workflow to help you get started with Actions

name: Build production

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build-pacifistabot-discord-and-restart-prod:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode clean package -Dmaven.javadoc.skip -T 6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pacifistabot discord pterodactyl dockerfile
        run: |
          docker build . --tag ghcr.io/pacifistamc/pacifistabot-discord-pteroq:latest -f pterodactyl-discord.Dockerfile
          docker push ghcr.io/pacifistamc/pacifistabot-discord-pteroq:latest

      - name: Send start signal to restart pacifistabot discord with new version
        run: |
          curl "https://${{ secrets.PTERODACTYL_DOMAIN }}/api/client/servers/61ec6ee9/power?signal=restart" \
            -X POST \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}'

  send-success-build-discord-notif:
    needs:
      - build-pacifistabot-discord-and-restart-prod

    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CI_STATUS }}
          DISCORD_USERNAME: PacifistaBot-Deploy
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/99340299?s=96&v=4
        uses: Ilshidur/action-discord@master
        with:
          args: '✅ PacifistaBot Discord à été déployé sur pterodactyl !'